version: "3.7"

services:
  b2b-front:
    image: chodzi/holidays:latest
    container_name: holidaysapp
    restart: always
    volumes:
      - "/app/node_modules"
      - ".:/app"

    environment:
      VIRTUAL_HOST: holidays.grawires.pl
      LETSENCRYPT_HOST: holidays.grawires.pl
      LETSENCRYPT_EMAIL: grawires@gmail.com

networks:
  default:
    external:
      name: nginx-proxy
